version: "3.7"
services:
 apache:
  build:
   context: './.docker/apache/'
  networks:
   - frontend
   - backend
  ports:
   - "14080:80"
  volumes:
   - ./public_html:/var/www/html
  depends_on:
   - php
   - db
  container_name: apache_service
 php:
  build:
   context: './.docker/php/'
  networks:
   - backend
  volumes:
   - ./public_html:/var/www/html
  container_name: php_service
 db:
  image: mariadb:10.5.10
  restart: always
  networks:
   - backend
  ports:
   - "13306:3306"
  volumes:
   - ./.docker/db/data:/var/lib/mysql
  environment:
   MARIADB_ROOT_PASSWORD: "rootpassword"
   MARIADB_DATABASE: "base"
   MARIADB_USER: "user"
   MARIADB_PASSWORD: "userpassword"   
  container_name: db_service
 phpmyadmin:
  image: phpmyadmin
  restart: always
  ports:
   - "14081:80"
  depends_on:
   - db
  environment:
   PMA_HOSTS: db
   MYSQL_ROOT_PASSWORD: "rootpassword"
   MYSQL_USER: "user"
   MYSQL_PASSWORD: "userpassword"
   UPLOAD_LIMIT: "256M"
   MAX_EXECUTION_TIME: 300
  networks:
   - backend
  container_name: phpmyadmin_service
networks:
 frontend:
 backend:
